<?php

return [
    'medical_bag' => ['label' => 'Medical bag', 'glyph' => '🩺'],
    'first_aid' => ['label' => 'First aid', 'glyph' => '✚'],
    'stethoscope' => ['label' => 'Stethoscope', 'glyph' => '🩺'],
    'hospital' => ['label' => 'Hospital', 'glyph' => '🏥'],
    'ambulance' => ['label' => 'Ambulance', 'glyph' => '🚑'],
    'pharmacy' => ['label' => 'Pharmacy', 'glyph' => '⚕'],
    'medicine' => ['label' => 'Medicine', 'glyph' => '💊'],
    'capsule' => ['label' => 'Capsules', 'glyph' => '💊'],
    'syringe' => ['label' => 'Syringes', 'glyph' => '💉'],
    'vaccine' => ['label' => 'Vaccines', 'glyph' => '💉'],
    'thermometer' => ['label' => 'Thermometers', 'glyph' => '🌡'],
    'heart' => ['label' => 'Cardiology', 'glyph' => '♥'],
    'ecg' => ['label' => 'ECG', 'glyph' => '〰'],
    'blood' => ['label' => 'Blood care', 'glyph' => '🩸'],
    'blood_pressure' => ['label' => 'Blood pressure', 'glyph' => '♥'],
    'glucose' => ['label' => 'Glucose meters', 'glyph' => '◈'],
    'oxygen' => ['label' => 'Oxygen', 'glyph' => 'O₂'],
    'lungs' => ['label' => 'Respiratory', 'glyph' => '🫁'],
    'inhaler' => ['label' => 'Inhalers', 'glyph' => '⌁'],
    'mask' => ['label' => 'Medical masks', 'glyph' => '▱'],
    'gloves' => ['label' => 'Medical gloves', 'glyph' => '✋'],
    'sanitizer' => ['label' => 'Sanitizers', 'glyph' => '♨'],
    'bandage' => ['label' => 'Bandages', 'glyph' => '🩹'],
    'wheelchair' => ['label' => 'Wheelchairs', 'glyph' => '♿'],
    'hospital_bed' => ['label' => 'Hospital beds', 'glyph' => '🛏'],
    'monitor' => ['label' => 'Patient monitors', 'glyph' => '▣'],
    'ventilator' => ['label' => 'Ventilators', 'glyph' => '⌁'],
    'defibrillator' => ['label' => 'Defibrillators', 'glyph' => 'ϟ'],
    'microscope' => ['label' => 'Microscopes', 'glyph' => '🔬'],
    'laboratory' => ['label' => 'Laboratory', 'glyph' => '⚗'],
    'test_tube' => ['label' => 'Test tubes', 'glyph' => '🧪'],
    'dna' => ['label' => 'Diagnostics', 'glyph' => '🧬'],
    'xray' => ['label' => 'X-ray', 'glyph' => '▧'],
    'ultrasound' => ['label' => 'Ultrasound', 'glyph' => '◉'],
    'surgery' => ['label' => 'Surgical supplies', 'glyph' => '✂'],
    'dental' => ['label' => 'Dental', 'glyph' => '🦷'],
    'eye' => ['label' => 'Ophthalmology', 'glyph' => '👁'],
    'ear' => ['label' => 'ENT', 'glyph' => '👂'],
    'brain' => ['label' => 'Neurology', 'glyph' => '◌'],
    'bone' => ['label' => 'Orthopedics', 'glyph' => '🦴'],
    'kidney' => ['label' => 'Kidney care', 'glyph' => '◖'],
    'maternity' => ['label' => 'Maternity', 'glyph' => '🤰'],
    'baby' => ['label' => 'Baby care', 'glyph' => '👶'],
    'elderly' => ['label' => 'Elderly care', 'glyph' => '♿'],
    'rehabilitation' => ['label' => 'Rehabilitation', 'glyph' => '↗'],
    'scale' => ['label' => 'Medical scales', 'glyph' => '⚖'],
    'uniform' => ['label' => 'Medical uniforms', 'glyph' => '♙'],
    'disposable' => ['label' => 'Disposables', 'glyph' => '◇'],
];
